version: '3.8'

services:
  # --- Database Service ---
  mongodb:
    image: mongo:latest
    container_name: mern-mongodb-prod
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-prod:/data/db
    restart: unless-stopped

  # --- Backend API Service ---
  backend:
    # Notice this is "image" instead of "build"! 
    # Replace <your_dockerhub_username> with your actual DockerHub username.
    image: <lakshan0>/mern-auth-backend:latest
    container_name: mern-backend-prod
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/mern-auth
      - JWT_SECRET=your_super_secret_jwt_key_change_me
      - JWT_EXPIRES_IN=30d
    depends_on:
      - mongodb
    restart: unless-stopped

  # --- Frontend React Web Service ---
  frontend:
    # Replace <your_dockerhub_username> with your actual DockerHub username.
    image: <lakshan0>/mern-auth-frontend:latest
    container_name: mern-frontend-prod
    ports:
      - "80:80" # Maps port 80 to Nginx port 80 inside container
    depends_on:
      - backend
    restart: unless-stopped

# --- Named Volumes ---
volumes:
  mongo-data-prod:
